FROM golang:alpine AS builder

WORKDIR /opt/server

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/server cmd/main.go

FROM alpine

WORKDIR /opt/server

COPY --from=builder /opt/server/bin/server bin/server
COPY --from=builder /opt/server/config.json config.json

RUN chmod +x bin/server

CMD ["./bin/server"]
